### PR TITLE
Rename all the repos and uppercase Pa11y

### PR DESCRIPTION
**Pull request by rowanmanning**
Addresses https://github.com/pa11y/org/issues/4

### CODE REVIEW

**Comment by andrewmee** [comment]
LGTM

**Comment by leenabora** [comment]
Hello People,

why am I receiving these emails? I have unsubscribed from every possible
source. Can you please unsubsribe me?
I am not related to this.

cheers,
L

**Comment by andrewmee** [comment]
Hi @leenabora,

Looks like you're watching this repo: https://github.com/pa11y/reporter-1.0-json/watchers  A mistaken click perhaps?

If you stop watching it you shouldn't be notified of any new changes to it.

Cheers,
Andrew

**Comment by leenabora** [comment]
Thanks. By any chance this project is related to springer?

**Comment by rowanmanning** [comment]
Yes, it used to sit under the SpringerNature GitHub account. Maybe that's why you were watching it originally :)

**Pull request merged**
